version: '3'

services:
  cqrs-api:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    networks:
      - kafka
    ports:
      - ${TOMCAT_PORT}:8080
    env_file:
      - ./.env
    restart: ${RESTART_SERVICE}
    depends_on:
      - mysql
  mysql:
    image: library/mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - kafka
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    restart: ${RESTART_SERVICE}

networks:
  kafka:
    external:
      name: dockerkafka_network

volumes:
  db-data: